name: Backend Tests

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: backend/requirements.txt
      - name: Install lint deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint
        run: flake8 . --ignore=E501,W503,E203,E302,E305,E402,E701,E702,E731,W291,W292,W293,W391,F401,F811

  # Run pytest tests after linting passes
  test:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: backend/requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx pytest-asyncio
      - name: Run tests
        run: |
          pytest -q

